### ISSUE TITLE
我想问下，如何 fork 你的包然后通过 composer 加载

### ISSUE THREAD

**Issue by shuliuzhenhua** [Rivsen/hello-world#6]
比如说我发现你的代码有问题，然后我把他fork到了自己的仓库，这种情况下，我应该如何通过 composer 加载我这个仓库呢。

**Comment by Rivsen** [comment]
fork之后用你的packagist帐号发布到自己名下就可以用composer了，或者修改 composer.json 指定包的仓库地址

**Comment by shuliuzhenhua** [comment]
第一个可以理解，第二个理解不来。
比如说你这个包。
`{
  "require": {
    "rivsen/hello-world": "https://github.com/shuliuzhenhua/hello-world-1"
  }
}
`
在 npm 里面可以直接这样改，可是在 composer 里面我就不知道了。网上查的方法，我不知道怎么试了没用。可以给我个你这个包的示例么网上找的方法，不知道怎么到我这里迷之没用。，多谢大佬。

**Comment by Rivsen** [comment]
composer的官方文档里有专门的一篇讲如何加载第三方来源的包，[戳这里](https://getcomposer.org/doc/05-repositories.md)

**Comment by shuliuzhenhua** [comment]
谢了。刚刚试了下解决了。以前看的文档，没解决，估计是我的理解能力提高了一些。[捂脸]
